# Generated by Django 4.2.6 on 2023-10-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livros_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='create_at',
        ),
    ]
